# GitHub Action to generate and deploy a snake animation based on GitHub contributions
name: Generate Snake Animation

# Triggers for the workflow
on:
  # Run daily at 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to the main branch
  push:
    branches:
      - main

# Permissions required for writing to the repository
permissions:
  contents: write

# Define the job
jobs:
  generate-and-deploy:
    name: Generate and Deploy Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for accurate contribution data

      # Step 2: Generate snake animation SVG
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Generate SVG outputs for light and dark themes
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg | dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages # Branch to deploy the animation
          build_dir: dist # Directory containing generated files
          keep_history: false # Clear previous history to reduce size
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Notify on failure (optional error reporting)
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              body: '❌ The snake animation workflow failed. Please check the logs for details.'
            })
